Repository Automattic/vip-container-images, pull requests merged in 2022-11, with the labels that each got.

#346 Update WordPress 6.1 to Official Release
  wordpress/versions.json
Labels: [Status] Ready to Merge

#347 fix(gha): Fix the "Unable to process file command 'output' successfully" error
  .github/workflows/update-wp-versions.yml
Labels: bug, [Status] Needs Review

#349 feat(wordpress): Add HyperDB
  wordpress/extra/db-config.php
  wordpress/extra/wp-content/db.php
Labels: [Status] Ready to Merge

#352 fix(dev-tools): Add a check to ensure that MySQL is online
  dev-tools/setup.sh
Labels: [Status] Needs Review

#360 WordPress: Update 6.1 to 6.1.1 and sort the versions in CI
  .github/workflows/update-wp-versions.yml
  wordpress/versions.json
Labels: [Status] Ready to Merge

#359 ci: Add a workflow to trigger Skeleton build
  .github/workflows/build-skeleton.yml
  skeleton/Dockerfile
Labels: [Status] Needs Review, github_actions

#366 feat(mu-plugins)!: Make the experimental image stable
  .github/workflows/build-mu-plugins.yml
  .github/workflows/mu-plugins.yml
  mu-plugins/Dockerfile
  mu-plugins/Dockerfile.exp
  mu-plugins/autoupdate.sh
  mu-plugins/run.sh
Labels: enhancement, [Status] Needs Review, docker, github_actions

#372 fix(mu-plugins): Fix entrypoint name
  mu-plugins/Dockerfile
  mu-plugins/run.sh
Labels: bug

#381 feat(php-fpm): Add support for MailHog
  php-fpm/Dockerfile.74
  php-fpm/Dockerfile.80
  php-fpm/Dockerfile.81
  php-fpm/Dockerfile.82
  php-fpm/rootfs74/usr/local/bin/run.sh
  php-fpm/rootfs80/usr/local/bin/run.sh
  php-fpm/rootfs81/usr/local/bin/run.sh
  php-fpm/rootfs82/usr/local/bin/run.sh
Labels: enhancement
