Repository Automattic/vip-container-images, pull requests merged in 2022-02, with the labels that each got.

#153 Enable Code Coverage Analysis with XDebug
  php-fpm/xdebug.ini
Labels: [Status] Needs Review, docker

#151 Workflow code to add extra tags to Docker image
  .github/workflows/wordpress.yml
Labels: [Status] Ready to Merge

#154 Update the dev-environment WordPress images, metadata and scripts
  wordpress/add-version.sh
  wordpress/del-version.sh
  wordpress/versions.json
Labels: [Status] Ready to Merge

#155 Bug fixes for WP Test Runner
  wp-test-runner/configure-environment.sh
  wp-test-runner/runner.sh
Labels: [Status] Needs Review, docker

#162 Bugfix - Missing WordPress Images post culling
  wordpress/versions.json
Labels: [Status] Ready to Merge

#163 CANTINA-844: synchronize PHP extensions with the production environment
  .github/workflows/php-fpm.yml
  php-fpm/Dockerfile
Labels: [Status] Ready to Merge, docker

#166 Separate 'pecl install' steps and clean up PEAR cache
  php-fpm/Dockerfile
Labels: [Status] Ready to Merge, docker

#165 Pull base images and properly scope cache
  .github/workflows/php-fpm.yml
  .github/workflows/wordpress.yml
Labels: docker
