Repository Automattic/vip-container-images, pull requests merged in 2023-02, with the labels that each got.

#415 Add welcome banner and improve terminal prompt for PHP-FPM containers
  php-fpm/Dockerfile.74
  php-fpm/Dockerfile.80
  php-fpm/Dockerfile.81
  php-fpm/Dockerfile.82
  php-fpm/rootfs-common/etc/vip-motd
  php-fpm/rootfs-common/home/www-data/.bashrc
  php-fpm/rootfs-common/root/.bashrc
Labels: [Status] Needs Review

#417 fix(dev-tools): Support MySQL 8 syntax for creating users
  dev-tools/setup.sh
Labels: [Status] Needs Review

#419 fix(dev-tools): Fix Host header for Codespaces
  dev-tools/dev-env-plugin.php
Labels: [Status] Needs Review

#420 fix(dev-tools): Fix Host header for Codespaces
  dev-tools/dev-env-plugin.php
  dev-tools/wp-config-defaults.php
Labels: [Status] Needs Review

#416 refactor(php-fpm): Deduplicate files
  php-fpm/rootfs-common/config/wp-cli.yaml
  php-fpm/rootfs-common/usr/local/bin/docker-php-entrypoint
  php-fpm/rootfs-common/usr/local/bin/run.sh
  php-fpm/rootfs74/usr/local/bin/run.sh
  php-fpm/rootfs80/config/wp-cli.yaml
  php-fpm/rootfs80/usr/local/bin/docker-php-entrypoint
  php-fpm/rootfs81/config/wp-cli.yaml
  php-fpm/rootfs81/usr/local/bin/docker-php-entrypoint
  php-fpm/rootfs81/usr/local/bin/run.sh
  php-fpm/rootfs82/config/wp-cli.yaml
  php-fpm/rootfs82/usr/local/bin/docker-php-entrypoint
  php-fpm/rootfs82/usr/local/bin/run.sh
Labels: [Status] Needs Review

#424 feat(php-fpm): Add ghostscript
  php-fpm/Dockerfile.74
  php-fpm/Dockerfile.80
  php-fpm/Dockerfile.81
  php-fpm/Dockerfile.82
Labels: enhancement, [Status] Ready to Merge

#422 chore(wordpress): Update drop-ins
  wordpress/extra/wp-content/db.php
  wordpress/extra/wp-content/object-cache.php
  wordpress/extra/wp-content/object-cache/object-cache-next.php
  wordpress/extra/wp-content/object-cache/object-cache-stable.php
  wordpress/extra/wp-content/wp-cache-memcached/.gitignore
  wordpress/extra/wp-content/wp-cache-memcached/bin/test.sh
  wordpress/extra/wp-content/wp-cache-memcached/composer.json
  wordpress/extra/wp-content/wp-cache-memcached/composer.lock
  wordpress/extra/wp-content/wp-cache-memcached/object-cache.php
  wordpress/extra/wp-content/wp-cache-memcached/phpcs.xml.dist
  wordpress/extra/wp-content/wp-cache-memcached/phpunit.xml.dist
  wordpress/extra/wp-content/wp-cache-memcached/psalm.xml.dist
  wordpress/extra/wp-content/wp-cache-memcached/stubs/memcached.php
  wordpress/extra/wp-content/wp-cache-memcached/tests/bootstrap.php
  wordpress/extra/wp-content/wp-cache-memcached/tests/class-object-cache.php
  wordpress/extra/wp-content/wp-cache-memcached/tests/test-object-cache.php
Labels: [Status] Needs Review

#437 fix(dev-tools): Fix demo app code detection when setting Enterprise Search constants
  dev-tools/setup.sh
Labels: bug
