Repository Automattic/vip-container-images, pull requests merged in 2023-03, with the labels that each got.

#439 Update object-cache-*.php files to match mu-plugins
  wordpress/extra/wp-content/object-cache-next.php
  wordpress/extra/wp-content/object-cache-stable.php
Labels: [Status] Ready to Merge

#445 fix(dev-tools): Fix detection of GitHub Codespaces
  dev-tools/wp-config-defaults.php
Labels: bug, [Status] Needs Review

#449 fix: Skip themes on WP install
  dev-tools/setup.sh
Labels: [Status] Ready to Merge

#450 chore(deps): Update ghcr.io/automattic/vip-container-images/alpine to 3.17.2
  dev-tools/Dockerfile
  skeleton/Dockerfile
  wordpress/Dockerfile
Labels: dependencies, [Status] Ready to Merge, docker

#451 Remove mariadb-lite image
  .github/workflows/mariadb-lite.yml
  mariadb-lite/Dockerfile
Labels: [Status] Ready to Merge
